[project]
name = "13-fastapi-uv-test"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.110.1",
    "uvicorn>=0.27.0",
    "pydantic>=2.7.0",
    "typing-extensions>=4.13.2"
]
